sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  # travis default rust test script
  - cargo build --verbose
  - cargo test --verbose
  # benches use the test feature which is only available on nightly
  # run benches once per build to detect performance regressions
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ] ; then
     cargo bench --verbose;
    fi
env:
  global:
    - secure: "eRqOvqFJkpV2uhp27Va2S1Tq6FUXdkoKRYrLnvcyO4eEry0Mjohc0T3M2syWNCJNupyUIECunYGUx3k6f2YtpdgQg0UndS67YZqUusFjnUNYUTR9KDwHE9MBS/df4x7dbGLqMX9PHi+Oo1wQXZhRb56s3K7CuV7GqqSXpt+FQ2qswugYfYpYzzYnlj0ak2YjgP65dZaFiR/p5awg6Vs1iWd1hPkfeyiDP9xXtPSrwgYoivv9RVkRIk0EZ7ak9e3710pQCMIafmZPuKTmSF/5BLUAHnu9EShMGaYnf5tSXmbFiqW6Jp+72EnbaEEAIoqbxuBRYJA/hqvnJY/DADT9Y4njwCqHJ6GWwe0+RzG0YKOx1Y19xXiercwuxllc7d+H4RU84NHH67JgcE91Btoj2bIrkLSoCiOcMEOITKbye299m7H1PQbf9D6AB0N8hCQYaQq0qKogwrBUx16KYcnvSSybHAJMCGPHcNiHyHMtiiyvgwOmB9aDH3BIlUlXDq18PrV+OreQ7TZL3D+DJ9s6F8P+DB+7ZFckVwxSCND5auDSMa4EyagQIjVNy56K4Tcwn2szF/bzPKpXwFMM7jo25F1nud9tox9k8ohjMStlgfcb6jS25xVDbeogteqKp6g/wjNSJBCOdxcVVNn1AYSgwptG8e3PmHRPrQ1VaeJj6t8="
# after success build rust documentation and push it to gh-pages branch
# only do this for the stable branch (once per build)
after_success: |
  if [ "$TRAVIS_RUST_VERSION" = "stable" ] ; then
    cargo doc --no-deps && \
    sudo pip install ghp-import && \
    ghp-import -n target/doc && \
    git push -qf https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
  fi
